# defined using the cerberus validation API
# https://docs.python-cerberus.org/en/stable/index.html

endpoint:
  type: string
  default: "localhost"
index_spec:
  type: string
max_num_segments:
  type: integer
  min: 1
  max: 10
index_thread_qty:
  type: integer
  min: 1
  max: 10
bulk_size:
  type: integer
  min: 1
  max: 10000
k:
  type: integer
  min: 1
  max: 10000
